language: scala

sudo: false

env:
  global:
    - secure: "kGHQxLZj8a2s5Fs9Z8CuDHUsd26u7cR8icUujffcXpcznJHrGyKcYCMmHbNH5ncQDIg0mtqrCmIV3xvjxHTRHt1JgseDRDTTAoshykBlSTeeUnfYAsYVRw/qU3dGN0fh11MNDigrj/80795Mmt6TwhspNQ/rE2Jg5p9PbHK5FA8="
    - secure: "f8eOm+ZvDJpmyEcAAjUQHiy2dV4VI9U2kOlytmeTM04qg1Y9KvuXtgTcaQ5MKXoA9Z6c14NAqoqwVrJSR3imItTLoz7fP+MazIPRpsaNONucndd9RPAhu6C8q+wkUQHWwJD6ZBDeSrJl2fM7wpVUQHFaLolUvmvuMEN3L002moY="

matrix:
  include:
    - script: sbt "++ 2.11.9" "benchmark RefBenchmark"
      jdk: oraclejdk8
    - script: sbt "++ 2.12.1" "benchmark RefBenchmark"
      jdk: oraclejdk8
    - script: sbt "++ 2.11.9" "benchmark IntBenchmark"
      jdk: oraclejdk8
    - script: sbt "++ 2.12.1" "benchmark IntBenchmark"
      jdk: oraclejdk8
    - script: sbt "++ 2.11.9" test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo publish ; fi)
      jdk: oraclejdk8
    - script: sbt "++ 2.10.6" test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo publish ; fi)
      jdk: oraclejdk8
    - script: sbt "++ 2.12.1" test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then echo publish ; fi)
      jdk: oraclejdk8
    - script: sbt "++ 2.10.6" compile printInfo test checkPackage
      jdk: oraclejdk8
